### ISSUE TITLE
Confusion with ordered tip states

### ISSUE THREAD

**Issue by amholtz** [TimBlokker/PhyCovA#3]
Hello, I am trying to use PhyCovA for my dataset. I have an ML tree with annotations for ancestral states. I cannot use this tree since it is not in the BEAST format for ancestral states, and it seems very complicated to reformat from a Newick annotated tree to one that would be accepted as a BEAST format. 

Alternatively, since this is just for a test of association, I can use the character reconstruction that is part of the application. This, however, required ordered tip states. I do not understand the order that these should be in. I have input my newick ML tree. I also have the matrix complete. I just need to input somewhere the accession numbers and their associated locations. I'm assuming this would be input in 'Sampling locations'. But it seems this only accepts a file with one column with tip locations in order.  My question is, what is this order supposed to be based off. 

Thank you for your help. 

All the best-
Andrew

**Comment by TimBlokker** [comment]
Hello Andrew,

The order of the tip-states should be the same as in tree$tip.labels. So if you look at the following toy example:

```r
tiplabels <- c("usa", "france", "netherlands")
orig_tree <- rtree(n = 3, tip.label = tiplabels)
orig_tree$tip.label
```
Then you should provide a 1 column text file with the order "usa" -> "france" -> "netherlands".

To create these files you could do:
```r
#write tree
write.nexus(orig_tree, file = "orig_tree")

#write tip states file
write.table(tiplabels, file = "tiplabels.txt",row.names = F, col.names = F)

#write matrix
dist_mat <- matrix(ncol=3, rnorm(9, mean = 4), nrow = 3)
colnames(dist_mat) <- tiplabels
rownames(dist_mat) <- tiplabels
write.csv(dist_mat, "dist_mat.csv")
```
If I display these files in PhyCovA:
![image](https://user-images.githubusercontent.com/45885819/195650572-2bcc82a3-737f-446e-afa9-20111cb813da.png)

Then usa is node 1,  france node 2 and the netherlands node 3 as before. 

However there is the treeio package and you could try transforming your tree to a beast format using the following 2 functions:
treeio::read.newick()
treeio::write.beast.newick()

Best,
Tim

**Comment by liamxg** [comment]
I extract the sampling location of ebola from the tip label of "ebola_not_annotated.tree" file in the "input" file, I find that some tip do not have location information, and the "ebola_sampling_locations.txt" have all the location, so where you get this full information, thanks. :) @TimBlokker
