### ISSUE TITLE
can not connect the server

### ISSUE THREAD

**Issue by liamxg** [TimBlokker/PhyCovA#4]
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/46078579/232969843-ae3f376c-c0be-4c78-b093-ddedc55a69da.png">

**Comment by liamxg** [comment]
@TimBlokker

**Comment by TimBlokker** [comment]
Hi @liamxg ,

I am not associated to the lab anymore and do not have access to the log of the server, but perhaps @GuyBaele can?
I can have a look at your input files, starting with taxa.txt fto understand if the error might originate there. Would you mind sharing it here?

**Comment by liamxg** [comment]
@TimBlokker thank you for your reply, I just use the input covid data.

**Comment by liamxg** [comment]
<img width="160" alt="image" src="https://user-images.githubusercontent.com/46078579/233229027-fd28a367-5ff3-427b-ac89-9e58315de879.png">

**Comment by liamxg** [comment]
hope you can help me out, thanks. :)

**Comment by GuyBaele** [comment]
I was getting the same error, but have now restarted the application and it seems to be working fine.

**Comment by liamxg** [comment]
@GuyBaele thanks.

**Comment by liamxg** [comment]
<img width="998" alt="image" src="https://user-images.githubusercontent.com/46078579/233337497-76804954-8c9d-4b15-bea9-d3ec878915c3.png">

**Comment by liamxg** [comment]
now it is also works for me. :)
